apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: notification
  name: notification
spec:
  ports:
  - name: 8083-8083
    port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: notification
  type: ClusterIP
status:
  loadBalancer: {}
