apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: notification
  name: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: notification
    spec:
      containers:
      - image: sit_ay23-24_csc3104-notification
        name: sit-ay23-24-csc3104-notification-nbl4d
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: travelexp-conf
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
status: {}
