# Use root/example as user/password credentials
version: '3.8'

services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - ${MONGO_PORT}:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    #   MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    #   MONGO_DB_USERNAME: ${MONGO_USER}
    #   MONGO_DB_PASSWORD: ${MONGO_PASSWORD}
