version: '3.8'

services:
  account:
    build:
      context: backend
      dockerfile: ./account/Dockerfile
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - account-mysqldb
  account-mysqldb:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_ACCOUNT_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  wishlist:
    build:
      context: backend
      dockerfile: ./wishlist/Dockerfile
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - wishlist-mongodb
  wishlist-mongodb:
    image: mongo
    restart: always
    container_name: wishlist-mongodb
    ports:
      - ${MONGO_WISHLIST_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_DB_USER: ${MONGO_USER}
      MONGO_DB_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  notification:
    build:
      context: backend
      dockerfile: ./notification/Dockerfile
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      - notification-mongodb
  notification-mongodb:
    image: mongo
    restart: always
    container_name: notification-mongodb
    ports:
      - ${MONGO_NOTIFICATION_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_DB_USER: ${MONGO_USER}
      MONGO_DB_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  friends:
    build:
      context: backend
      dockerfile: ./friends/Dockerfile
    restart: always
    ports:
      - "8084:8084"
    depends_on:
      - friends-mongodb
  friends-mongodb:
    image: mongo
    restart: always
    container_name: friends-mongodb
    ports:
      - ${MONGO_FRIENDS_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_DB_USER: ${MONGO_USER}
      MONGO_DB_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  client:
    build:
      context: frontend
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - account
    stdin_open: true
    tty: true
