version: "3.8"
services:
  mongodb:
    image: "mongo"
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: password
  account:
    build: ./backend/account
    restart: always
    ports:
      - "9191:9191"
    depends_on:
      - mysqldb
    volumes:
      - ./backend/account:/app
  mysqldb:
    image: "mysql"
    restart: always
    volumes:
      - mysqldb_data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: spring_boot
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  react:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - account
volumes:
  mongodb_data:
  mysqldb_data:
