apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: account-mysqldb
  name: account-mysqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-mysqldb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: account-mysqldb
    spec:
      containers:
      - image: mysql
        name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
          - name: MYSQL_DATABASE
            value: account
          - name: MYSQL_USER
            value: csc3104
          - name: MYSQL_PASSWORD
            value: csc3104
        # envFrom:
        # - configMapRef:
        #     name: travelexp-conf
        resources: {}
status: {}
