// // Generated by the protocol buffer compiler.  DO NOT EDIT!
// // source: travel-management.proto

// package com.csc3104.grpc;

// public interface POIDetailsOrBuilder extends
//     // @@protoc_insertion_point(interface_extends:com.csc3104.grpc.POIDetails)
//     com.google.protobuf.MessageOrBuilder {

//   /**
//    * <code>string name = 1;</code>
//    * @return The name.
//    */
//   java.lang.String getName();
//   /**
//    * <code>string name = 1;</code>
//    * @return The bytes for name.
//    */
//   com.google.protobuf.ByteString
//       getNameBytes();

//   /**
//    * <code>string category = 2;</code>
//    * @return The category.
//    */
//   java.lang.String getCategory();
//   /**
//    * <code>string category = 2;</code>
//    * @return The bytes for category.
//    */
//   com.google.protobuf.ByteString
//       getCategoryBytes();

//   /**
//    * <code>string address = 3;</code>
//    * @return The address.
//    */
//   java.lang.String getAddress();
//   /**
//    * <code>string address = 3;</code>
//    * @return The bytes for address.
//    */
//   com.google.protobuf.ByteString
//       getAddressBytes();

//   /**
//    * <code>string imageUrl = 4;</code>
//    * @return The imageUrl.
//    */
//   java.lang.String getImageUrl();
//   /**
//    * <code>string imageUrl = 4;</code>
//    * @return The bytes for imageUrl.
//    */
//   com.google.protobuf.ByteString
//       getImageUrlBytes();
// }
