server:
  port: 9090
spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: account_auth
          uri: http://account:8081
          predicates:
            - Path=/api/v1/auth/**

        - id: account_userinfo
          uri: http://account:8081
          predicates:
            - Path=/api/v1/user/**

        - id: wishlist
          uri: http://wishlist:8082
          predicates:
            - Path=/api/v1/gallery/**
          filters:
            - AuthenticationFilter

        - id: notification
          uri: http://notification:8083
          predicates:
            - Path=/notification/**
          filters:
            - AuthenticationFilter

        - id: events
          uri: http://notification:8083
          predicates:
            - Path=/events/**
          filters:
            - AuthenticationFilter

        - id: friends
          uri: http://friends:8084
          predicates:
            - Path=/friends/**
          filters:
            - AuthenticationFilter
