server:
  port: 8081
grpc:
  server:
    port: 8089
spring:
  datasource:
    url: jdbc:mysql://account-mysqldb:3306/account
    username: csc3104
    password: csc3104
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
