server:
  port: 8084
grpc:
  client:
    account-service:
      address: account:8089
      negotiation-type: plaintext
spring:
  data:
    mongodb:
      database: travelexp
      host: friends-mongodb
      port: 27017
      username: csc3104
      password: csc3104
