server:
  port: 8082
spring:
  data:
    mongodb:
      database: travelexp
      host: wishlist-mongodb
      port: 27017
      username: csc3104
      password: csc3104
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# spring.data.mongodb.username=${env.MONGO_ROOT_USER}
# spring.data.mongodb.password=${env.MONGO_ROOT_PASSWORD}

# Yelp Fusion API Configuration
# api.baseurl=https://api.yelp.com/v3
# api.key=T-x0gy1cReiguaj6wrR7t3Bbh1VLvXOdQtqWD5S_utPY-MSF55xx5HSe916Ffh3l3HufmaMviu-ty2XUKTLeyta6v2MkWOX0I3H7sOWUOOWQM_OVdCrPMIGS3SI6ZXYx
