apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: client
    spec:
      containers:
      - image: sit_ay23-24_csc3104-client
        name: sit-ay23-24-csc3104-client
        imagePullPolicy: Never
        resources: {}
status: {}
