apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: client
  name: client
spec:
  ports:
  - name: web
    port: 5173
    protocol: TCP
    targetPort: 5173
    nodePort: 30002
  selector:
    app: client
  type: NodePort
status:
  loadBalancer: {}
