apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: friends-mongodb
  name: friends-mongodb
spec:
  ports:
  - name: 27019-27017
    port: 27019
    protocol: TCP
    targetPort: 27017
  selector:
    app: friends-mongodb
  type: ClusterIP
status:
  loadBalancer: {}
