apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: friends
  name: friends
spec:
  ports:
  - name: web
    port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    app: notification
  type: ClusterIP
status:
  loadBalancer: {}
