apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gateway
    spec:
      containers:
      - image: sit_ay23-24_csc3104-gateway
        name: sit-ay23-24-csc3104-gateway-8b6ll
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: travelexp-conf
        resources: {}
status: {}
