apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wishlist
  name: wishlist
spec:
  ports:
  - name: web
    port: 8082
    protocol: TCP
    targetPort: 8082
  - name: grpc
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: wishlist
  type: ClusterIP
status:
  loadBalancer: {}
