apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wishlist
  name: wishlist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wishlist
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wishlist
    spec:
      containers:
      - image: huilun2000/csc3104:sit_ay23-24_csc3104-wishlist
        name: sit-ay23-24-csc3104-wishlist
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: travelexp-conf
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
status: {}
