apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: account
  name: account
spec:
  ports:
  - name: web
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: grpc
    port: 8089
    protocol: TCP
    targetPort: 8089
  selector:
    app: account
  type: ClusterIP
status:
  loadBalancer: {}
