apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: account
  name: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: account
    spec:
      containers:
      - image: huilun2000/csc3104:sit-ay23-24-csc3104-account
        name: sit-ay23-24-csc3104-gateway
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: travelexp-conf
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
status: {}
