apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: account-mysqldb
  name: account-mysqldb
spec:
  ports:
  - name: 3306-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: account-mysqldb
  type: ClusterIP
status:
  loadBalancer: {}
