server:
  port: 8083
grpc:
  client:
    poi-service:
      address: static://localhost:8082
      negotiation-type: plaintext
spring:
  application:
    name: notification
  data:
    mongodb:
      database: travelexp
      host: notification-mongodb
      port: 27017
      username: csc3104
      password: csc3104
  mail:
    host: smtp.gmail.com
    port: 587
    username: w08277427@gmail.com
    password: inqq zlpy tmji drol
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
