apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: standard
  hostPath:
    path: /Users/huilunang/Desktop/Projects/SIT-UOG/2023_2024_TRI1/SIT_AY23-24_CSC3104/db