apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wishlist
  name: wishlist
spec:
  ports:
  - name: 8082-8082
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: wishlist
  type: ClusterIP
status:
  loadBalancer: {}
