package com.csc3104.poi.grpc;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: travel-management.proto

public interface POIRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:POIRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string businessId = 1;</code>
   * @return The businessId.
   */
  java.lang.String getBusinessId();
  /**
   * <code>string businessId = 1;</code>
   * @return The bytes for businessId.
   */
  com.google.protobuf.ByteString
      getBusinessIdBytes();
}
